name: Build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        container: ["ros:melodic", "ros:noetic"]
    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v1
      - name: update git
        run: |
          apt-get update 
          apt-get install -y software-properties-common
          add-apt-repository ppa:git-core/ppa
          apt-get update
          apt-get install -y git

      - name: rosdep install
        run: |
          apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: catkin build
        shell: bash
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          catkin build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: catkin build run_tests
        shell: bash
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          catkin build --verbose --catkin-make-args run_tests
          catkin_test_results
